name: GPT Access Automation

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use GPT Token for API Access
        run: |
          echo "Using GPT Token for authorized API access."
          curl -H "Authorization: token ${{ secrets.GPT_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/contents/
